#!/bin/sh

# default monitor is LVDS-1

HOST=$(uname -n)
echo $HOST

if [ $HOST == "acer" ]; then
    echo "Acer detected"
    MONITOR1=eDP1
    MONITOR2=HDMI2
elif [ $HOST == "x230" ]; then
    echo "X230 detected"
    MONITOR1=LVDS-1
    MONITOR2=VGA-1
else
    echo "ERROR: Unrecognised host to get monitors, expected acer/x230"
    return -1
fi;

# functions to switch from laptop to main monitor and vice versa
ActivateMain() {
    echo "Activate main"
    if [ $HOST = "acer" ]; then
        xrandr --output $MONITOR2 --auto --rotate left --output $MONITOR1 --off
    else
        xrandr --output $MONITOR2 --auto --output $MONITOR1 --off
    fi;
}
ActivateLaptop() {
    echo "Activate laptop"
    xrandr --output $MONITOR2 --off --output $MONITOR1 --auto
}

# functions to check if VGA is connected and in use
MainNotConnected() {
    ! xrandr | grep $MONITOR2 | grep disconnected
}

# actual script
if MainNotConnected
then
    ActivateMain
else
    ActivateLaptop
fi
