#!/bin/sh

# Mount hard-drive
HOST=$(uname -n)

echo host: $HOST
if [ $HOST = 'x230' ]; then
    doas mkdir -p /mnt/usb-hdd && cmd doas mount_msdosfs /dev/da0s1 /mnt/usb-hdd
else
    cmd "ERROR: not implemented, not sure where the hard drive is located!"
fi
