#!/bin/sh

if pgrep "wpa_supplicant" ; then
	sudo pkill -9 wpa_supplicant
fi

if pgrep "dhcpcd" ; then
	sudo pkill -9 dhcpcd
fi

# start wireless
sudo wpa_supplicant -Dnl80211 -iwlp2s0 -c/home/ryan/4g.conf -B;
sudo dhcpcd wlp2s0;
notify-send "Switching to mobile net"
