#!/bin/sh

# Restart synergy if running or start it a-fresh

DISPLAY=:0
HOST=$(uname -n)
SHOST=192.168.1.72

if [ $HOST = "x230" ]; then
	doas pkill -9 synergyc
	synergyc -f $SHOST > $HOME/synergy.log
	msg "Restarted synergyc"
else
	doas pkill -9 synergys
	cmd synergys --config $HOME/barrier.conf;
	msg "Restarted synergys"
fi
