#!/bin/sh

HOST=$(uname -n)
while true
do
   if [ $HOST = "x230" ]; then
	CPU=$(ps -o %cpu -p `pgrep -S idle` | awk 'NR==2{printf("CPU: %.2f%s" ,400 / $1, "%")}')
    BAT=$(apm | awk 'NR==5{printf("BAT: %s", $4)}')
	TIME=$(date '+%Y %b %d (%a) %I:%M%p')
	WEATHER1=$( weather )
    STATUS="$CPU | $BAT | $TIME | $WEATHER1"
	xsetroot -name "$STATUS"
    sleep 2;
   else
        CPU=$(top -b -n1 | grep "Cpu(s)" | awk '{print $2 + $4}' | tr -d '\n')
	MEM=$(free -h | sed -n '2{p;q}' | awk '{print $3 "/" $2}')
	TIME=$(date '+%Y %b %d (%a) %I:%M%p')
	WEATHER1=$( weather )
	STATUS="Cpu: $CPU | Mem: $MEM | $TIME | $WEATHER1"
        xsetroot -name "$STATUS"
        sleep 2;
    fi
done


